artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/lakshmanbhaarathi/Poultry-Disease-Classification/raw/main/data1.zip
  local_data_file: artifacts/data_ingestion/data1.zip
  unzip_dir: artifacts/data_ingestion
